### ISSUE TITLE
New Release Needed

### ISSUE THREAD

**Issue by whoenig** [bitcraze/crazyradio2-firmware#2]
For Crazyswarm2 (or any crazyflie-link-cpp user), we need a new release which includes @ataffanel [fix](https://github.com/bitcraze/crazyradio2-firmware/commit/fa81a66359b78b01648cf1c668c0cb42a622c003), see discussion in https://github.com/bitcraze/crazyflie-link-cpp/issues/37#issuecomment-1695456575.

The release should also bump up the version number, so we can actually add a proper check in crazyflie-link-cpp, since we can only support dongles that are flashed with Arnaud's fix.

**Comment by knmcguire** [comment]
Hi! We are planning to do another overall release somewhere in October so we will make sure to add Crazyradio to that as well.

**Comment by ataffanel** [comment]
Version 1.1 released!
